Traverse the source zarr store copying the groups and attributes into…
pangeo-data/rechunker pull request #134
Opened 2023-02-17 23:10 UTC by flamingbear

:wave: hey there.  I looked into this a bit for my work and wanted to leave this for someone in case they thought it was useful.  In my work, I'm still using v0.5 and running this basic command after the rechunk happens to pick up all of the missing group metadata. Hope this is helpful. If I get some time I will try to update with some tests if this seems useful.

2023-02-18 22:02 UTC, rabernat commented
Welcome Mike and thanks for your contribution! I agree this seems useful.

I don't understand why the test workflow did not run on this PR. 🤔

2023-02-20 15:10 UTC, flamingbear commented
CI didn't kick off, because actions weren't enabled on my fork. I pushed a space change to run them.

2023-02-20 15:19 UTC, rabernat commented
Awesome!

If you can add a test for this, happy to merge it.

2023-02-20 15:21 UTC, flamingbear commented
There's some CI permission stuff it looks like I'll have to dig into. Thanks.

2023-02-20 15:22 UTC, rabernat commented
I'm guessing that some of the test failures we are seeing are due to a regression with Zarr.

2023-02-20 18:24 UTC, rabernat commented
Perfect, CI is back in good shape. Now we just need a test that covers this new feature and we're good to go! 🚀

2023-02-20 18:27 UTC, flamingbear commented
Appreciate it.  I will take a look and see if I can make sense of the tests.

2023-02-20 22:37 UTC, flamingbear commented
@rabernat I hope this was you were looking for.  Hmm.  I thought I saw a bad coverage pop up. I didn't unit test, but added a second group test where it seemed reasonable to me.

2023-02-21 15:10 UTC, rabernat requested changes
Just one small request...

2023-02-21 15:17 UTC, flamingbear commented on tests/test_rechunk.py
> +        assert target_root[attr_loc].attrs["description"] == attr_value
I'm happy to do that, I just didn't want to mix up the previous test with my stuff, but yes, it's totally duplicative.

2023-03-14 15:03 UTC, merged

2023-03-14 15:10 UTC, rabernat commented
I just released 0.5.1, which has this in it.